package com.shengpay.mcl.bp.api;

import java.net.MalformedURLException;
import java.net.URL;
import javax.xml.namespace.QName;
import javax.xml.ws.WebEndpoint;
import javax.xml.ws.WebServiceClient;
import javax.xml.ws.WebServiceFeature;
import javax.xml.ws.Service;

/**
 * This class was generated by Apache CXF 3.1.9
 * 2016-12-28T12:09:22.387+08:00
 * Generated source version: 3.1.9
 * 
 */
@WebServiceClient(name = "BatchPaymentService", 
                  wsdlLocation = "http://mtc.shengpay.com/services/BatchPayment/BatchPayment?wsdl",
                  targetNamespace = "http://api.bp.mcl.shengpay.com/") 
public class BatchPaymentService extends Service {

    public final static URL WSDL_LOCATION;

    public final static QName SERVICE = new QName("http://api.bp.mcl.shengpay.com/", "BatchPaymentService");
    public final static QName BatchPaymentPort = new QName("http://api.bp.mcl.shengpay.com/", "BatchPaymentPort");
    static {
        URL url = null;
        try {
            url = new URL("http://mtc.shengpay.com/services/BatchPayment/BatchPayment?wsdl");
        } catch (MalformedURLException e) {
            java.util.logging.Logger.getLogger(BatchPaymentService.class.getName())
                .log(java.util.logging.Level.INFO, 
                     "Can not initialize the default wsdl from {0}", "http://mtc.shengpay.com/services/BatchPayment/BatchPayment?wsdl");
        }
        WSDL_LOCATION = url;
    }

    public BatchPaymentService(URL wsdlLocation) {
        super(wsdlLocation, SERVICE);
    }

    public BatchPaymentService(URL wsdlLocation, QName serviceName) {
        super(wsdlLocation, serviceName);
    }

    public BatchPaymentService() {
        super(WSDL_LOCATION, SERVICE);
    }
    
    public BatchPaymentService(WebServiceFeature ... features) {
        super(WSDL_LOCATION, SERVICE, features);
    }

    public BatchPaymentService(URL wsdlLocation, WebServiceFeature ... features) {
        super(wsdlLocation, SERVICE, features);
    }

    public BatchPaymentService(URL wsdlLocation, QName serviceName, WebServiceFeature ... features) {
        super(wsdlLocation, serviceName, features);
    }    




    /**
     *
     * @return
     *     returns BatchPayment
     */
    @WebEndpoint(name = "BatchPaymentPort")
    public BatchPayment getBatchPaymentPort() {
        return super.getPort(BatchPaymentPort, BatchPayment.class);
    }

    /**
     * 
     * @param features
     *     A list of {@link javax.xml.ws.WebServiceFeature} to configure on the proxy.  Supported features not in the <code>features</code> parameter will have their default values.
     * @return
     *     returns BatchPayment
     */
    @WebEndpoint(name = "BatchPaymentPort")
    public BatchPayment getBatchPaymentPort(WebServiceFeature... features) {
        return super.getPort(BatchPaymentPort, BatchPayment.class, features);
    }

}
