
package com.shengpay.mcl.bp.api;

/**
 * Please modify this class to meet your needs
 * This class is not complete
 */

import java.io.File;
import java.net.MalformedURLException;
import java.net.URL;
import javax.xml.namespace.QName;
import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.xml.bind.annotation.XmlSeeAlso;
import javax.xml.ws.RequestWrapper;
import javax.xml.ws.ResponseWrapper;

/**
 * This class was generated by Apache CXF 3.1.9
 * 2016-12-28T12:09:22.314+08:00
 * Generated source version: 3.1.9
 * 
 */
public final class BatchPayment_BatchPaymentPort_Client {

    private static final QName SERVICE_NAME = new QName("http://api.bp.mcl.shengpay.com/", "BatchPaymentService");

    private BatchPayment_BatchPaymentPort_Client() {
    }

    public static void main(String args[]) throws java.lang.Exception {
        URL wsdlURL = BatchPaymentService.WSDL_LOCATION;
        if (args.length > 0 && args[0] != null && !"".equals(args[0])) { 
            File wsdlFile = new File(args[0]);
            try {
                if (wsdlFile.exists()) {
                    wsdlURL = wsdlFile.toURI().toURL();
                } else {
                    wsdlURL = new URL(args[0]);
                }
            } catch (MalformedURLException e) {
                e.printStackTrace();
            }
        }
      
        BatchPaymentService ss = new BatchPaymentService(wsdlURL, SERVICE_NAME);
        BatchPayment port = ss.getBatchPaymentPort();  
        
        {
        System.out.println("Invoking query...");
        com.shengpay.mcl.bp.api.QueryRequest _query_arg0 = null;
        com.shengpay.mcl.btc.response.QueryResponse _query__return = port.query(_query_arg0);
        System.out.println("query.result=" + _query__return);


        }
        {
        System.out.println("Invoking apply...");
        com.shengpay.mcl.bp.api.BatchPaymentRequest _apply_arg0 = null;
        com.shengpay.mcl.btc.response.BatchPaymentResponse _apply__return = port.apply(_apply_arg0);
        System.out.println("apply.result=" + _apply__return);


        }
        {
        System.out.println("Invoking generate...");
        com.shengpay.mcl.bp.api.GenerateResultRequest _generate_arg0 = null;
        com.shengpay.mcl.btc.response.GenerateResultResponse _generate__return = port.generate(_generate_arg0);
        System.out.println("generate.result=" + _generate__return);


        }
        {
        System.out.println("Invoking dateRangePaginationQuery...");
        com.shengpay.mcl.bp.api.DateRangePaginationQueryRequest _dateRangePaginationQuery_arg0 = null;
        com.shengpay.mcl.btc.response.DateRangePaginationQueryResponse _dateRangePaginationQuery__return = port.dateRangePaginationQuery(_dateRangePaginationQuery_arg0);
        System.out.println("dateRangePaginationQuery.result=" + _dateRangePaginationQuery__return);


        }
        {
        System.out.println("Invoking dateRangeQuery...");
        com.shengpay.mcl.bp.api.DateRangeQueryRequest _dateRangeQuery_arg0 = null;
        com.shengpay.mcl.btc.response.DateRangeQueryResponse _dateRangeQuery__return = port.dateRangeQuery(_dateRangeQuery_arg0);
        System.out.println("dateRangeQuery.result=" + _dateRangeQuery__return);


        }
        {
        System.out.println("Invoking directApply...");
        com.shengpay.mcl.bp.api.DirectApplyRequest _directApply_arg0 = null;
        com.shengpay.mcl.btc.response.DirectApplyResponse _directApply__return = port.directApply(_directApply_arg0);
        System.out.println("directApply.result=" + _directApply__return);


        }

        System.exit(0);
    }

}
